version: "3.4"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: TodoList
    ports:
      - 5432:5432
    networks:
      - todo-list-network
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - 9999:9999
    networks:
      - todo-list-network
    depends_on:
      - db
networks:
  todo-list-network:
    driver: bridge
